package main

import (
	"crypto/rand"
	"fmt"
	"math/big"
	//"math/rand"
)

func main() {
	//rand.Seed(time.Now().UnixNano())
	//since random number is generated by computer it tend to lean towards a specific number
	// if we dont use rand.Seed(30) it will give more 1 but if we use it we will get more 3
	//algorithm is driven by Seed so we change it to truly random number so we use time(it keeps changing)
	//fmt.Println(rand.Intn(5)) // generate random number
	//random from crypto
	myRandomNum, _ := rand.Int(rand.Reader, big.NewInt(5))
	fmt.Println(myRandomNum)
}
